
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jose
 */
public class simplex extends javax.swing.JFrame {

    /**
     * Creates new form simplex
     */
    public simplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filas = new javax.swing.JTextField();
        columnas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SIMPLEX");

        filas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasActionPerformed(evt);
            }
        });

        jLabel2.setText("FILAS");

        jLabel3.setText("COLUMNAS");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        jButton1.setText("Generar Matriz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("RESULTADO PASO A PASO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(columnas)
                            .addComponent(filas))
                        .addGap(89, 89, 89)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(columnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        int fila = Integer.parseInt(filas.getText());
        int columna = Integer.parseInt(columnas.getText());
        int columna1 = columna;
        for(int i = 0; i<columna;i++){
            model.addColumn("x"+(i+1));
        }
        columna = fila+columna;
        model.setRowCount(fila);
        model.setColumnCount(columna);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        text.append("Metodo Simplex\n");
        DecimalFormat I = new DecimalFormat("0.000");
        int fila=Integer.parseInt(filas.getText());
        int columna=Integer.parseInt(columnas.getText());
        int columna1=columna;
        columna=fila+columna;
        double v[][]= new double [fila][columna];
        int y1=1;
        for (int i = 0; i < columna; i++) {
            if (i<columna1) {
                text.append("\tX"+(i+1));
            }else if (i>=columna1 && i<columna-1) {
                text.append("\tX"+(y1));
                y1++;
            }else{
                text.append("\tresul");
            }
        }
        text.append("\n");
        for (int i = 0; i < fila; i++) {
            for (int j = 0; j < columna; j++) {
                v[i][j]=Double.parseDouble(tabla.getValueAt(i, j).toString());
            }
        }
        for (int i = 0; i < fila; i++) {
            if (i!=0) {
                text.append("d"+i);
            }
            for (int j = 0; j < columna; j++) {
                text.append("\t"+I.format(v[i][j]));
            }
            text.append("\n");
        }
        text.append("\n\n");
        String v2[]=new String[fila];
        int v3[]=new int[fila];
        int v4[]=new int[fila];
        
        int co=0;
        while(true){
            if (co==columna1) {
                break;
            }
            int f=0,c=0;
            double negativo=0;
            for (int i = 0; i < columna; i++) {
                if (v[0][i]<negativo) {
                    negativo=v[0][i];
                    c=i;
                }
            }
            text.append("HALLAMOS EL MINIMO VALOR PARA LA COLUMNA PIVOTAL...\n");
            text.append(""+negativo+"\nla columna es\n");
            for (int i = 0; i < fila; i++) {
                text.append(""+v[i][c]+"\n");
            }
            text.append("\n");
            text.append("\nDividiendo la columna\n");
            double menor=0;
            double v1[]= new double[fila-1];
            int h=0;
            for (int i = 0; i < fila; i++) {
                v1[h]=v[i][columna-1]/v[i][c];
                text.append(""+v[i][columna-1]+"/"+v[i][c]+"="+v1[h]+"\n");
                h++;
            }
            menor=v1[0];
            for (int i = 0; i < fila; i++) {
                if (v1[i]<=menor) {
                    menor=v1[i];
                    f=i+1;
                }
            }
            text.append("El menor de la division es:"+menor+"\n");
            double pivo=v[f][c];
            text.append("El pivo es:"+pivo);
            
            text.append("\nProceso de convertir el pivote en 1\ndividiendo toda la fila con el pivote\n");
            for (int i = 0; i < columna; i++) {
                double va=v[f][i];
                v[f][i]=v[f][i]/pivo;
                text.append(""+va+"/"+pivo+"="+v[f][i]+"\n");
            }
            for (int i = 0; i < fila; i++) {
                if (i==f) {
                    v2[i]="X"+(c+1);
                    v3[i]=c+1;
                    v4[i]=i;
                }
                if (v3[i]<=0) {
                    v2[i]="d"+(i);
                }
            }
            text.append("\nProceso\n");
            for (int i = 0; i < fila; i++) {
                if (i!=f) {
                    text.append("Convirtiendo la columna del pivote en cero, en fila"+(i+1)+"\n\n");
                    double guar=0;
                    guar=v[i][c];
                    for (int j = 0; j < columna; j++) {
                        double vaa=v[i][j];
                        v[i][j]=guar*v[f][j]+v[i][j];
                        text.append(""+guar+"*"+v[f][j]+"+"+vaa+"="+v[i][j]+"\n");
                    }
                }
            }
            co=0;
            for (int i = 0; i < columna1; i++) {
                if (v[0][i]>=0) {
                    co++;
                }
            }
            y1=1;
            for (int i = 0; i < columna; i++) {
                if (i<columna1) {
                    text.append("\tX"+(i+1));
                }else if (i>=columna1 && i<columna-1) {
                    text.append("\td"+(y1));
                }else{
                    text.append("\tresul");
                }
            }
            text.append("\n");
            for (int i = 0; i < fila; i++) {
                if (i!=0) {
                    text.append(v2[i]);
                }
                for (int j = 0; j < columna; j++) {
                    text.append("\t"+I.format(v[i][j]));
                }
                text.append("\n");
            }
            text.append("\n\n");
        }
        int y2=0;
        text.append("Resultado...\n");
        text.append("Z="+v[0][columna-1]+"\n");
        for (int i = 1; i < fila; i++) {
            char m1[]= v2[i].toCharArray();
            if (m1[0]=='X') {
                text.append(""+v2[i]+"="+v[v4[i]][columna-1]+"\n");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField columnas;
    private javax.swing.JTextField filas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
